# Create this file in `mkdir -p /etc/prometheus` folder.
global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'openstack'
    openstack_sd_configs:
      - role: 'instance'
        region: 'RegionOne'
        identity_endpoint: 'http://10.80.81.1:5000/v3/'
        username: 'j.caviedes'
        domain_id: 'default'
        project_name: 'k8s PoC ORAN'
        password: 'JC22062020cv'
    relabel_configs:
      - source_labels: [__meta_openstack_public_ip]
        target_label: __address__
        replacement: '$1:9100'
      - source_labels: [__meta_openstack_tag_prometheus]
        regex: true.*
        action: keep
      - source_labels: [__meta_openstack_tag_node_exporter]
        regex: true.*
        action: keep
      - action: labelmap
        regex: __meta_openstack_(.+)
